name: build
on:
  push:
    paths: 
      - '**.js'
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: \${{ matrix.node }} 
    - run: npm ci 
    - run: npm run build --if-present
